sudo: false
language: java
jdk:
  - oraclejdk8
services:
  - redis-server
script:
  - mvn test -P unitTest -pl currency-converter
  - mvn test -P domainIntegrationTest -pl currency-converter
  - mvn test -P serviceIntegrationTest -pl currency-converter
  - mvn test -P apiTest -pl currency-converter
  - mvn test -pl currency-converter-sync
