language: java
jdk:
  - oraclejdk7
services:
  - redis-server
script:
  - mvn test -P unitTest -pl currency-converter-persistence
  - mvn test -P domainIntegrationTest -pl currency-converter-persistence
  - mvn test -pl currency-converter-sync
