// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.apilytc.persistence.domain;

import org.apilytc.persistence.domain.CurrencyIntegrationTest;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect CurrencyIntegrationTest_Roo_Configurable {
    
    declare @type: CurrencyIntegrationTest: @Configurable;
    
}
