// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.apilytc.currency.persistence.domain;

import java.math.BigInteger;
import java.util.Iterator;
import java.util.List;

import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;

import org.apilytc.currency.persistence.domain.Currency;
import org.apilytc.currency.persistence.domain.CurrencyDataOnDemand;
import org.apilytc.currency.persistence.domain.CurrencyIntegrationTest;
import org.apilytc.currency.persistence.repository.CurrencyRepository;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;

privileged aspect CurrencyIntegrationTest_Roo_IntegrationTest {
    
    declare @type: CurrencyIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: CurrencyIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    @Autowired
    CurrencyDataOnDemand CurrencyIntegrationTest.dod;
    
    @Autowired
    CurrencyRepository CurrencyIntegrationTest.currencyRepository;
    
    @Test
    public void CurrencyIntegrationTest.testCount() {
        Assert.assertNotNull("Data on demand for 'Currency' failed to initialize correctly", dod.getRandomCurrency());
        long count = currencyRepository.count();
        Assert.assertTrue("Counter for 'Currency' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void CurrencyIntegrationTest.testFind() {
        Currency obj = dod.getRandomCurrency();
        Assert.assertNotNull("Data on demand for 'Currency' failed to initialize correctly", obj);
        BigInteger id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Currency' failed to provide an identifier", id);
        obj = currencyRepository.findOne(id);
        Assert.assertNotNull("Find method for 'Currency' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Currency' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void CurrencyIntegrationTest.testFindAll() {
        Assert.assertNotNull("Data on demand for 'Currency' failed to initialize correctly", dod.getRandomCurrency());
        long count = currencyRepository.count();
        Assert.assertTrue("Too expensive to perform a find all test for 'Currency', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Currency> result = currencyRepository.findAll();
        Assert.assertNotNull("Find all method for 'Currency' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Currency' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void CurrencyIntegrationTest.testFindEntries() {
        Assert.assertNotNull("Data on demand for 'Currency' failed to initialize correctly", dod.getRandomCurrency());
        long count = currencyRepository.count();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Currency> result = currencyRepository.findAll(new org.springframework.data.domain.PageRequest(firstResult / maxResults, maxResults)).getContent();
        Assert.assertNotNull("Find entries method for 'Currency' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Currency' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void CurrencyIntegrationTest.testSave() {
        Assert.assertNotNull("Data on demand for 'Currency' failed to initialize correctly", dod.getRandomCurrency());
        Currency obj = dod.getNewTransientCurrency(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Currency' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Currency' identifier to be null", obj.getId());
        try {
            currencyRepository.save(obj);
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        Assert.assertNotNull("Expected 'Currency' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void CurrencyIntegrationTest.testDelete() {
        Currency obj = dod.getRandomCurrency();
        Assert.assertNotNull("Data on demand for 'Currency' failed to initialize correctly", obj);
        BigInteger id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Currency' failed to provide an identifier", id);
        obj = currencyRepository.findOne(id);
        currencyRepository.delete(obj);
        Assert.assertNull("Failed to remove 'Currency' with identifier '" + id + "'", currencyRepository.findOne(id));
    }
    
}
