// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.apilytic.currency.csv;

import org.apilytic.currency.csv.CsvReaderAdapter;

privileged aspect CsvReaderAdapter_Roo_JavaBean {
    
    public void CsvReaderAdapter.setStringReader(String stringReader) {
        this.stringReader = stringReader;
    }
    
}
