// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.apilytc.domain;

import org.apilytc.domain.CurrencyDataOnDemand;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect CurrencyDataOnDemand_Roo_Configurable {
    
    declare @type: CurrencyDataOnDemand: @Configurable;
    
}
