// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.apilytc.domain;

import org.apilytc.domain.Currency;

privileged aspect Currency_Roo_JavaBean {
    
    public String Currency.getMessage() {
        return this.message;
    }
    
    public void Currency.setMessage(String message) {
        this.message = message;
    }
    
}
