// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.apilytc.domain;

import org.apilytc.domain.CurrencyExchange;

privileged aspect CurrencyExchange_Roo_JavaBean {
    
    public String CurrencyExchange.getTitle() {
        return this.title;
    }
    
    public void CurrencyExchange.setTitle(String title) {
        this.title = title;
    }
    
}
